//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Extradition
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Period { get; set; }
        public int Workwea_code { get; set; }
    
        public virtual Workwea Workwea { get; set; }
    }
}
